# springcloud
eureka:
  instance:
      hostname: 192.168.0.230
      port: 8761
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
     
spring:
  application:
    name: eureka-provider-dev
  profiles:
    active: dev
      
fileName:
  application-dev.yml
